In [1]:
from IPython.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [2]:
#########SC, FC 이름 맞추기

import os
#print(os.listdir(file_dir))
import pandas as pd
import numpy as np
file_dir = '/scratch/connectome/dyhan316/TVB/IIT_Desikan/'

a = pd.read_csv(file_dir+'label_use_killain.txt', delimiter = "\t", header = None)
FC_names = a.iloc[:,3].to_list()
#print(FC_names) #new_names = FC names
#print(len(FC_names))
SC_names = pd.read_csv('/scratch/connectome/dyhan316/TVB/virtual_aging_brain/data/external/Schaefer2018_100Parcels_7Networks_tab.txt',
                      delimiter = '\t', header = None)
SC_names = SC_names.iloc[:,1]
SC_names = SC_names.values
#print(SC_names)
#print(len(SC_names))

conversion = pd.read_csv('/scratch/connectome/dyhan316/TVB/desikan_SC_FC_conversion.txt',
                        delimiter = ' ', names = ['name1','name2'])
#print(conversion)
conversion.set_index('name2', inplace = True)


conversion['name2'] = conversion.index
SC_names_conv = []
for i in range(len(SC_names)):
    SC_names_conv.append(SC_names[i].split('-')[0] + '.' + SC_names[i].split('-')[1])

conversion_ROI_name = []
for ROI_name in SC_names_conv:
    cond = conversion['name1'] == ROI_name
    conversion_ROI_name.append(conversion.loc[cond, 'name2'].values[0])


where_indexer = []
for i in range(len(conversion_ROI_name)):
    where_ind = np.where(np.array(FC_names) == conversion_ROI_name[i])[0][0]
    where_indexer.append(where_ind)
FC_names_reorder = []
for ind in where_indexer:
    FC_names_reorder.append(FC_names[ind])
pd.concat([pd.DataFrame(FC_names_reorder), pd.DataFrame(conversion_ROI_name), pd.DataFrame(SC_names)], axis=1).head(60)
where_indexer #원래 FC 가 7번인게 SC의 0번째 => 바꾸는 룰 이 있다
print([i for i in where_indexer]) #the where indexer

#검사 : 밑의 구개가 일치한다
print(FC_names[7], SC_names[0])

[7, 6, 16, 2, 17, 0, 18, 19, 20, 21, 46, 5, 24, 49, 22, 23, 27, 26, 25, 28, 29, 4, 35, 37, 39, 30, 32, 33, 34, 3, 31, 36, 38, 40, 41, 42, 45, 43, 44, 1, 47, 48, 15, 14, 50, 10, 51, 8, 52, 53, 54, 55, 80, 13, 58, 83, 56, 57, 61, 60, 59, 62, 63, 12, 69, 71, 73, 64, 66, 67, 68, 11, 65, 70, 72, 74, 75, 76, 79, 77, 78, 9, 81, 82]
Left-Accumbens-area L-AC


In [13]:
import numpy as np
import os

input_dir = '/storage/bigdata/ABCD/fmriprep/1.rs_fmri/5.ROI_DATA/'
save_dir = '/scratch/connectome/dyhan316/TVB/virtual_aging_brain/data/external/Julich/'

sub_list = os.listdir(save_dir)
print(len(sub_list))
#sksk = np.load(input_dir+'sub-NDARINV01EN91PG/desikankilliany_sub-NDARINV01EN91PG.npy') #sample data 
#print(os.listdir(save_dir)[:10])

def rearrange_func_data(fc_data, arrange_rule):
    new_array = np.zeros(fc_data.shape)
    for i in range(fc_data.shape[1]):
        new_array[:,i] = fc_data[:,arrange_rule[i]]
    return new_array

for subj in os.listdir(save_dir):
    ### save 1 : for notebook #3
    #save_file_path = os.path.join(save_dir, subj, "ses-1/FC/","{}_meanTS_GS_bptf_Schaefer100_7NW.txt".format(subj))
    
    ###save 2: for notebook#4
    save_file_path = os.path.join(save_dir, subj, "ses-1/FC/","{}_meanTS_Schaefer7NW400p.txt".format(subj))
    #print(save_file_path)#_meanTS_Schaefer7NW400p.txt
    
    fc_data = np.load(input_dir+"sub-{}/desikankilliany_sub-{}.npy".format(subj,subj))
    new_array = rearrange_func_data(fc_data, where_indexer)
    np.savetxt(save_file_path, new_array)
    #print("\n",np.all(new_array[:,0]-fc_data[:,7]==0)) #as we can see, it's true!!! (becareful, columnwise!)
    



new_array = np.zeros(sksk.shape)
print(new_array)
print(new_array.shape)
for i in range(sksk.shape[1]):
    print(where_indexer[i], end=" ")
    new_array[:,i] = sksk[:,where_indexer[i]]
print("\n",np.all(new_array[:,0]-sksk[:,7]==0)) #as we can see, it's true!!! (becareful, columnwise!)
#print(sksk.shape)
#for i in range(sksk.shape[1]):
##이제 이것 보내기만 하면됨!@

8238


NameError: name 'sksk' is not defined

In [12]:
a = np.loadtxt('/scratch/connectome/dyhan316/TVB/virtual_aging_brain/data/external/Julich/NDARINV1U58UMN8/ses-1/FC/NDARINV1U58UMN8_meanTS_Schaefer7NW400p.txt') 
print(a.shape)
a = np.savetxt('/scratch/connectome/dyhan316/TVB/virtual_aging_brain/data/external/Julich/NDARINV1U58UMN8/ses-1/FC/NDARINV1U58UMN8_meanTS_Schaefer7NW400p.txt', a)
a = np.loadtxt('/scratch/connectome/dyhan316/TVB/virtual_aging_brain/data/external/Julich/NDARINV1U58UMN8/ses-1/FC/NDARINV1U58UMN8_meanTS_Schaefer7NW400p.txt') 
print(a.shape)


(373, 84)
(373, 84)


In [7]:
import numpy as np
#a=np.loadtxt('/scratch/connectome/dyhan316/TVB/virtual_aging_brain/data/temporary_result/NDARINVP7YTV29E.txt')
a = np.arange(16).reshape(4,4)
print(a)

rsFC_emp   = np.corrcoef(a.T)#np.corrcoef(bold_emp.T)
rsFC_emp   = rsFC_emp * (rsFC_emp>0)
rsFC_emp   = rsFC_emp - np.diag(np.diagonal(rsFC_emp))
print(rsFC_emp)
FC_FC_homo         =  np.diag(rsFC_emp,k=4)
print(FC_FC_homo)
print("============")
b = np.arange(16).reshape(2,8)
print(b)

rsFC_emp   = np.corrcoef(b.T)#np.corrcoef(bold_emp.T)
rsFC_emp   = rsFC_emp * (rsFC_emp>0)
rsFC_emp   = rsFC_emp - np.diag(np.diagonal(rsFC_emp))
print(rsFC_emp)
FC_FC_homo         =  np.diag(rsFC_emp,k=4)
print(FC_FC_homo)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0. 1. 1. 1.]
 [1. 0. 1. 1.]
 [1. 1. 0. 1.]
 [1. 1. 1. 0.]]
[]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]
[[0. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 1. 1. 1. 1. 1.]
 [1. 1. 0. 1. 1. 1. 1. 1.]
 [1. 1. 1. 0. 1. 1. 1. 1.]
 [1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 1. 1. 0. 1. 1.]
 [1. 1. 1. 1. 1. 1. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 0.]]
[1. 1. 1. 1.]


In [45]:
##################checking if same names (remove later)

d = '/scratch/connectome/dyhan316/TVB/virtual_aging_brain/data/external/Julich'

separator   = ''
file_julich = separator.join([d,'/',subj,'/ses-1/FC/',subj,'_meanTS_GS_bptf_Schaefer100_7NW.txt'])
print(file_julich)
#bold        = np.loadtxt(file_julich)
print("/scratch/connectome/dyhan316/TVB/virtual_aging_brain/data/external/Julich/NDARINV2YUK5D0D/ses-1/FC/NDARINV2YUK5D0D_meanTS_GS_bptf_Schaefer100_7NW.txt"
     =="/scratch/connectome/dyhan316/TVB/virtual_aging_brain/data/external/Julich/NDARINV2YUK5D0D/ses-1/FC/NDARINV2YUK5D0D_meanTS_GS_bptf_Schaefer100_7NW.txt")

/scratch/connectome/dyhan316/TVB/virtual_aging_brain/data/external/Julich/NDARINV2YUK5D0D/ses-1/FC/NDARINV2YUK5D0D_meanTS_GS_bptf_Schaefer100_7NW.txt
True


In [9]:
print(sksk.shape)

(373, 84)


In [ ]:
import numpy as np
import os

directory = '/storage/bigdata/ABCD/fmriprep/1.rs_fmri/5.ROI_DATA/'

#rois=['Left-Cerebellum-Cortex', 'Left-Thalamus-Proper', 'Left-Caudate', 'Left-Putamen', 'Left-Pallidum', 'Left-Hippocampus', 'Left-Amygdala', 'Left-Accumbens-area', 'Right-Cerebellum-Cortex', 'Right-Thalamus-Proper', 'Right-Caudate', 'Right-Putamen', 'Right-Pallidum', 'Right-Hippocampus', 'Right-Amygdala"', 'Right-Accumbens-area', 'ctx-lh-bankssts', 'ctx-lh-caudalanteriorcingulate', 'ctx-lh-caudalmiddlefrontal', 'ctx-lh-cuneus', 'ctx-lh-entorhinal', 'ctx-lh-fusiform', 'ctx-lh-inferiorparietal', 'ctx-lh-inferiortemporal', 'ctx-lh-isthmuscingulate', 'ctx-lh-lateraloccipital', 'ctx-lh-lateralorbitofrontal', 'ctx-lh-lingual', 'ctx-lh-medialorbitofrontal', 'ctx-lh-middletemporal', 'ctx-lh-parahippocampal', 'ctx-lh-paracentral', 'ctx-lh-parsopercularis', 'ctx-lh-parsorbitalis', 'ctx-lh-parstriangularis', 'ctx-lh-pericalcarine', 'ctx-lh-postcentral', 'ctx-lh-posteriorcingulate', 'ctx-lh-precentral', 'ctx-lh-precuneus', 'ctx-lh-rostralanteriorcingulate', 'ctx-lh-rostralmiddlefrontal', 'ctx-lh-superiorfrontal', 'ctx-lh-superiorparietal', 'ctx-lh-superiortemporal', 'ctx-lh-supramarginal', 'ctx-lh-frontalpole', 'ctx-lh-temporalpole', 'ctx-lh-transversetemporal', 'ctx-lh-insula', 'ctx-rh-bankssts', 'ctx-rh-caudalanteriorcingulate', 'ctx-rh-caudalmiddlefrontal', 'ctx-rh-cuneus', 'ctx-rh-entorhinal', 'ctx-rh-fusiform', 'ctx-rh-inferiorparietal', 'ctx-rh-inferiortemporal', 'ctx-rh-isthmuscingulate', 'ctx-rh-lateraloccipital', 'ctx-rh-lateralorbitofrontal', 'ctx-rh-lingual', 'ctx-rh-medialorbitofrontal', 'ctx-rh-middletemporal', 'ctx-rh-parahippocampal', 'ctx-rh-paracentral', 'ctx-rh-parsopercularis', 'ctx-rh-parsorbitalis', 'ctx-rh-parstriangularis', 'ctx-rh-pericalcarine', 'ctx-rh-postcentral', 'ctx-rh-posteriorcingulate', 'ctx-rh-precentral', 'ctx-rh-precuneus', 'ctx-rh-rostralanteriorcingulate', 'ctx-rh-rostralmiddlefrontal', 'ctx-rh-superiorfrontal', 'ctx-rh-superiorparietal', 'ctx-rh-superiortemporal', 'ctx-rh-supramarginal', 'ctx-rh-frontalpole', 'ctx-rh-temporalpole', 'ctx-rh-transversetemporal', 'ctx-rh-insula']['Background', 'Left-Cerebellum-Cortex', 'Left-Thalamus-Proper', 'Left-Caudate', 'Left-Putamen', 'Left-Pallidum', 'Left-Hippocampus', 'Left-Amygdala', 'Left-Accumbens-area', 'Right-Cerebellum-Cortex', 'Right-Thalamus-Proper', 'Right-Caudate', 'Right-Putamen', 'Right-Pallidum', 'Right-Hippocampus', 'Right-Amygdala"', 'Right-Accumbens-area', 'ctx-lh-bankssts', 'ctx-lh-caudalanteriorcingulate', 'ctx-lh-caudalmiddlefrontal', 'ctx-lh-cuneus', 'ctx-lh-entorhinal', 'ctx-lh-fusiform', 'ctx-lh-inferiorparietal', 'ctx-lh-inferiortemporal', 'ctx-lh-isthmuscingulate', 'ctx-lh-lateraloccipital', 'ctx-lh-lateralorbitofrontal', 'ctx-lh-lingual', 'ctx-lh-medialorbitofrontal', 'ctx-lh-middletemporal', 'ctx-lh-parahippocampal', 'ctx-lh-paracentral', 'ctx-lh-parsopercularis', 'ctx-lh-parsorbitalis', 'ctx-lh-parstriangularis', 'ctx-lh-pericalcarine', 'ctx-lh-postcentral', 'ctx-lh-posteriorcingulate', 'ctx-lh-precentral', 'ctx-lh-precuneus', 'ctx-lh-rostralanteriorcingulate', 'ctx-lh-rostralmiddlefrontal', 'ctx-lh-superiorfrontal', 'ctx-lh-superiorparietal', 'ctx-lh-superiortemporal', 'ctx-lh-supramarginal', 'ctx-lh-frontalpole', 'ctx-lh-temporalpole', 'ctx-lh-transversetemporal', 'ctx-lh-insula', 'ctx-rh-bankssts', 'ctx-rh-caudalanteriorcingulate', 'ctx-rh-caudalmiddlefrontal', 'ctx-rh-cuneus', 'ctx-rh-entorhinal', 'ctx-rh-fusiform', 'ctx-rh-inferiorparietal', 'ctx-rh-inferiortemporal', 'ctx-rh-isthmuscingulate', 'ctx-rh-lateraloccipital', 'ctx-rh-lateralorbitofrontal', 'ctx-rh-lingual', 'ctx-rh-medialorbitofrontal', 'ctx-rh-middletemporal', 'ctx-rh-parahippocampal', 'ctx-rh-paracentral', 'ctx-rh-parsopercularis', 'ctx-rh-parsorbitalis', 'ctx-rh-parstriangularis', 'ctx-rh-pericalcarine', 'ctx-rh-postcentral', 'ctx-rh-posteriorcingulate', 'ctx-rh-precentral', 'ctx-rh-precuneus', 'ctx-rh-rostralanteriorcingulate', 'ctx-rh-rostralmiddlefrontal', 'ctx-rh-superiorfrontal', 'ctx-rh-superiorparietal', 'ctx-rh-superiortemporal', 'ctx-rh-supramarginal', 'ctx-rh-frontalpole', 'ctx-rh-temporalpole', 'ctx-rh-transversetemporal', 'ctx-rh-insula']
#print(len(rois))
aa = os.listdir(directory+'sub-NDARINV01EN91PG')

sksk = np.load(directory+'sub-NDARINV01EN91PG/desikankilliany_sub-NDARINV01EN91PG.npy')

new_array = np.zeros(sksk.shape)
print(new_array)
print(new_array.shape)
for i in range(sksk.shape[1]):
    print(where_indexer[i], end=" ")
    new_array[:,i] = sksk[:,where_indexer[i]]
print("\n",np.all(new_array[:,0]-sksk[:,7]==0)) #as we can see, it's true!!! (becareful, columnwise!)
#print(sksk.shape)
#for i in range(sksk.shape[1]):
##이제 이것 보내기만 하면됨!@


##########backup

In [2]:
from nilearn import datasets

In [3]:
dataset = datasets.fetch_development_fmri(n_subjects=1)
func_filename = dataset.func[0]



In [4]:
atlas = datasets.fetch_atlas_harvard_oxford('cort-maxprob-thr25-2mm')
print('The atlas contains {} non-overlapping regions'.format(
    len(atlas.labels) - 1))

The atlas contains 48 non-overlapping regions


In [5]:
from nilearn.input_data import NiftiLabelsMasker
masker = NiftiLabelsMasker(atlas.maps,
                           labels=atlas.labels,
                           standardize=True)
masker.fit()

report = masker.generate_report()
report

/home/connectome/dyhan316/.local/lib/python3.8/site-packages/nilearn/input_data/__init__.py:27: FutureWarning: The import path 'nilearn.input_data' is deprecated in version 0.9. Importing from 'nilearn.input_data' will be possible at least until release 0.13.0. Please import from 'nilearn.maskers' instead.
  warnings.warn(message, FutureWarning)
/home/connectome/dyhan316/.local/lib/python3.8/site-packages/nilearn/maskers/nifti_labels_masker.py:305: UserWarning: No image provided to fit in NiftiLabelsMasker. Plotting ROIs of label image on the MNI152Template for reporting.
  warnings.warn(msg)
/home/connectome/dyhan316/.local/lib/python3.8/site-packages/nilearn/plotting/img_plotting.py:348: FutureWarning: Default resolution of the MNI template will change from 2mm to 1mm in version 0.10.0
  anat_img = load_mni152_template()


In [6]:
print(atlas.labels)
print(type(atlas.maps))
print(atlas.maps)
print('+++++++++++++++++++++++++++++')
print(len(['Background', 'Frontal Pole', 'Insular Cortex', 'Superior Frontal Gyrus', 'Middle Frontal Gyrus', 'Inferior Frontal Gyrus, pars triangularis', 'Inferior Frontal Gyrus, pars opercularis', 'Precentral Gyrus', 'Temporal Pole', 'Superior Temporal Gyrus, anterior division', 'Superior Temporal Gyrus, posterior division', 'Middle Temporal Gyrus, anterior division', 'Middle Temporal Gyrus, posterior division', 'Middle Temporal Gyrus, temporooccipital part', 'Inferior Temporal Gyrus, anterior division', 'Inferior Temporal Gyrus, posterior division', 'Inferior Temporal Gyrus, temporooccipital part', 'Postcentral Gyrus', 'Superior Parietal Lobule', 'Supramarginal Gyrus, anterior division', 'Supramarginal Gyrus, posterior division', 'Angular Gyrus', 'Lateral Occipital Cortex, superior division', 'Lateral Occipital Cortex, inferior division', 'Intracalcarine Cortex', 'Frontal Medial Cortex', 'Juxtapositional Lobule Cortex (formerly Supplementary Motor Cortex)', 'Subcallosal Cortex', 'Paracingulate Gyrus', 'Cingulate Gyrus, anterior division', 'Cingulate Gyrus, posterior division', 'Precuneous Cortex', 'Cuneal Cortex', 'Frontal Orbital Cortex', 'Parahippocampal Gyrus, anterior division', 'Parahippocampal Gyrus, posterior division', 'Lingual Gyrus', 'Temporal Fusiform Cortex, anterior division', 'Temporal Fusiform Cortex, posterior division', 'Temporal Occipital Fusiform Cortex', 'Occipital Fusiform Gyrus', 'Frontal Operculum Cortex', 'Central Opercular Cortex', 'Parietal Operculum Cortex', 'Planum Polare', "Heschl's Gyrus (includes H1 and H2)", 'Planum Temporale', 'Supracalcarine Cortex', 'Occipital Pole']))

['Background', 'Frontal Pole', 'Insular Cortex', 'Superior Frontal Gyrus', 'Middle Frontal Gyrus', 'Inferior Frontal Gyrus, pars triangularis', 'Inferior Frontal Gyrus, pars opercularis', 'Precentral Gyrus', 'Temporal Pole', 'Superior Temporal Gyrus, anterior division', 'Superior Temporal Gyrus, posterior division', 'Middle Temporal Gyrus, anterior division', 'Middle Temporal Gyrus, posterior division', 'Middle Temporal Gyrus, temporooccipital part', 'Inferior Temporal Gyrus, anterior division', 'Inferior Temporal Gyrus, posterior division', 'Inferior Temporal Gyrus, temporooccipital part', 'Postcentral Gyrus', 'Superior Parietal Lobule', 'Supramarginal Gyrus, anterior division', 'Supramarginal Gyrus, posterior division', 'Angular Gyrus', 'Lateral Occipital Cortex, superior division', 'Lateral Occipital Cortex, inferior division', 'Intracalcarine Cortex', 'Frontal Medial Cortex', 'Juxtapositional Lobule Cortex (formerly Supplementary Motor Cortex)', 'Subcallosal Cortex', 'Paracingulate

In [7]:
import nibabel as nib
file_dir = '/scratch/connectome/dyhan316/TVB/IIT_Desikan/'

######try_1
try_1 = nib.load(file_dir+'IIT_GM_Desikan_atlas_256.nii.gz')

masker = NiftiLabelsMasker(try_1,
                           standardize=True)
masker.fit()

report = masker.generate_report()
report
#print(atlas.maps)


/home/connectome/dyhan316/.local/lib/python3.8/site-packages/nilearn/maskers/nifti_labels_masker.py:305: UserWarning: No image provided to fit in NiftiLabelsMasker. Plotting ROIs of label image on the MNI152Template for reporting.
  warnings.warn(msg)


In [8]:
#####try_2
try_2 = nib.load(file_dir + 'IIT_GM_Desikan_atlas.nii.gz')
masker = NiftiLabelsMasker(try_2,
                           standardize=True)
masker.fit("MNI256")

report = masker.generate_report()
report



ValueError: File not found: 'MNI256'

In [10]:
import os
print(os.listdir(file_dir))
import pandas as pd
a = pd.read_csv(file_dir+'label_use_killain.txt', delimiter = "\t", header = None)
new_names = a.iloc[:,3].to_list()
#pd.read_csv(file_dir+'LUT_GM_Desikan_0to255.txt', sep = " ")

['IIT_GM_Desikan_mask.nii.gz', 'label_probabilities_Desikan.zip', 'IIT_GM_Desikan_confidence.nii.gz', 'label_probabilities_Desikan_256.zip', 'IIT_GM_Desikan_prob_256.nii.gz', 'IIT_GM_Desikan_mask_256.nii.gz', 'IIT_GM_Desikan_prob.nii.gz', 'IIT_GM_Desikan_atlas.nii.gz', 'IIT_GM_Desikan_atlas_256.nii.gz', 'label_use_killain.txt', 'LUT_GM_Desikan_0to1.txt', 'LUT_GM_Desikan_0to255.txt', '.ipynb_checkpoints', 'IIT_GM_Desikan_confidence_256.nii.gz']


In [11]:
new_list = ['Background']+new_names
print(new_list)
print(len(new_list))


['Background', 'Left-Cerebellum-Cortex', 'Left-Thalamus-Proper', 'Left-Caudate', 'Left-Putamen', 'Left-Pallidum', 'Left-Hippocampus', 'Left-Amygdala', 'Left-Accumbens-area', 'Right-Cerebellum-Cortex', 'Right-Thalamus-Proper', 'Right-Caudate', 'Right-Putamen', 'Right-Pallidum', 'Right-Hippocampus', 'Right-Amygdala"', 'Right-Accumbens-area', 'ctx-lh-bankssts', 'ctx-lh-caudalanteriorcingulate', 'ctx-lh-caudalmiddlefrontal', 'ctx-lh-cuneus', 'ctx-lh-entorhinal', 'ctx-lh-fusiform', 'ctx-lh-inferiorparietal', 'ctx-lh-inferiortemporal', 'ctx-lh-isthmuscingulate', 'ctx-lh-lateraloccipital', 'ctx-lh-lateralorbitofrontal', 'ctx-lh-lingual', 'ctx-lh-medialorbitofrontal', 'ctx-lh-middletemporal', 'ctx-lh-parahippocampal', 'ctx-lh-paracentral', 'ctx-lh-parsopercularis', 'ctx-lh-parsorbitalis', 'ctx-lh-parstriangularis', 'ctx-lh-pericalcarine', 'ctx-lh-postcentral', 'ctx-lh-posteriorcingulate', 'ctx-lh-precentral', 'ctx-lh-precuneus', 'ctx-lh-rostralanteriorcingulate', 'ctx-lh-rostralmiddlefrontal',

## SC, FC 이름맞추기

In [ ]:
['L-AC', 'L-AM', 'L-BSTS', 'L-CA', 'L-CACG', 'L-CER', 'L-CMFG', 'L-CU', 'L-EC', 'L-FG', 'L-FP', 'L-HI', 'L-ICG', 'L-IN', 'L-IPG', 'L-ITG', 'L-LG', 'L-LOFG', 'L-LOG', 'L-MOFG', 'L-MTG', 'L-PA', 'L-PCAL', 'L-PCG', 'L-PCU', 'L-PHIG', 'L-POP', 'L-POR', 'L-PTR', 'L-PU', 'L-PaCG', 'L-PoCG', 'L-PrCG', 'L-RACG', 'L-RMFG', 'L-SFG', 'L-SMG', 'L-SPG', 'L-STG', 'L-TH', 'L-TP', 'L-TTG', 'R-AC', 'R-AM', 'R-BSTS', 'R-CA', 'R-CACG', 'R-CER', 'R-CMFG', 'R-CU', 'R-EC', 'R-FG', 'R-FP', 'R-HI', 'R-ICG', 'R-IN', 'R-IPG', 'R-ITG', 'R-LG', 'R-LOFG', 'R-LOG', 'R-MOFG', 'R-MTG', 'R-PA', 'R-PCAL', 'R-PCG', 'R-PCU', 'R-PHIG', 'R-POP', 'R-POR', 'R-PTR', 'R-PU', 'R-PaCG', 'R-PoCG', 'R-PrCG', 'R-RACG', 'R-RMFG', 'R-SFG', 'R-SMG', 'R-SPG', 'R-STG', 'R-TH', 'R-TP', 'R-TTG']