In [1]:
import bct

BCT threshold_proportional 공부

In [2]:
import numpy as np
a = np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [3]:
b = a/np.max(a)
b

array([[0.        , 0.06666667, 0.13333333, 0.2       ],
       [0.26666667, 0.33333333, 0.4       , 0.46666667],
       [0.53333333, 0.6       , 0.66666667, 0.73333333],
       [0.8       , 0.86666667, 0.93333333, 1.        ]])

In [4]:
bct.threshold_proportional(a, 0.9)

array([[ 0,  0,  2,  3],
       [ 4,  0,  6,  7],
       [ 8,  9,  0, 11],
       [12, 13, 14,  0]])

In [5]:
bct.threshold_proportional(b,0.9)

array([[0.        , 0.        , 0.13333333, 0.2       ],
       [0.26666667, 0.        , 0.4       , 0.46666667],
       [0.53333333, 0.6       , 0.        , 0.73333333],
       [0.8       , 0.86666667, 0.93333333, 0.        ]])

bct threshold에 대한 결과:

* diagonal은 0으로 된다
* a든 b 둘다 똑같은 똑같은 결과를 낸다

In [6]:
np.sum(bct.threshold_proportional(b,0.1))/(np.sum(b)-b[1,1]-b[2,2]-b[3,3])
#구체적으로 어떤 역할을 하는지는 모르겠다

0.15555555555555556

In [7]:
bct.threshold_absolute(a,3)

array([[ 0,  0,  0,  3],
       [ 4,  0,  6,  7],
       [ 8,  9,  0, 11],
       [12, 13, 14,  0]])

In [8]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [9]:
help(bct.charpath)

Help on function charpath in module bct.algorithms.distance:

charpath(D, include_diagonal=False, include_infinite=True)
    The characteristic path length is the average shortest path length in
    the network. The global efficiency is the average inverse shortest path
    length in the network.
    
    Parameters
    ----------
    D : NxN np.ndarray
        distance matrix
    include_diagonal : bool
        If True, include the weights on the diagonal. Default value is False.
    include_infinite : bool
        If True, include infinite distances in calculation
    
    Returns
    -------
    lambda : float
        characteristic path length
    efficiency : float
        global efficiency
    ecc : Nx1 np.ndarray
        eccentricity at each vertex
    radius : float
        radius of graph
    diameter : float
        diameter of graph
    
    Notes
    -----
    The input distance matrix may be obtained with any of the distance
    functions, e.g. distance_bin, distance_wei.


In [10]:
c = np.array([[3,0,1],
              [2,5,0],
              [0,0,0]])

In [11]:
bct.threshold_proportional(c, 0.2)

array([[0, 0, 0],
       [2, 0, 0],
       [0, 0, 0]])

In [12]:
np.sum(c!=0)

4

In [17]:
print (0<(None))

TypeError: '<' not supported between instances of 'int' and 'NoneType'

In [ ]:
bc