## get network feature

In [2]:
import pandas as pd
import numpy as np
import scipy.io
import os
import sys

In [3]:
data_dir = './rDCM_outputs_8180/'
mat_list = os.listdir(data_dir)

FileNotFoundError: [Errno 2] No such file or directory: './rDCM_outputs_8180/'

In [13]:
sample = scipy.io.loadmat(os.path.join(data_dir+mat_list[3]))

In [4]:
import bct

In [81]:
np.array([density[0], transitivity_wd, efficiency_wei, assortativity_wei, rich_club_wd[-1], core_periphery_dir[-1], charpath[0]])

array([ 1.02083333e+00,  1.30595012e-03, -3.91142407e-05,  3.01225867e-02,
       -7.48685800e-01,  1.38000143e-01,  5.90499099e-03])

In [82]:
sublist=[]
nwmeasure = np.zeros((len(mat_list), 7))
for i in range(len(mat_list)):
    sub_id = mat_list[i].split('-')[1].split('.')[0]
    sublist.append(sub_id)
    
    sample = scipy.io.loadmat(os.path.join(data_dir+mat_list[i]))
    density = bct.density_dir(sample['result'])
    
    
    transitivity_wd = bct.transitivity_wd(sample['result'])
    
    
    efficiency_wei = bct.efficiency_wei(sample['result'])
    

    assortativity_wei = bct.assortativity_wei(sample['result'])
    

    rich_club_wd = bct.rich_club_wd(sample['result'])
    

    core_periphery_dir = bct.core_periphery_dir(sample['result'])
    

    charpath = bct.charpath(sample['result'])
    
    
    nwmeasure[i] = np.array([density[0], transitivity_wd, efficiency_wei,
                             assortativity_wei, rich_club_wd[-1], core_periphery_dir[-1], charpath[0]])

In [83]:
df = pd.concat([pd.DataFrame(sublist),pd.DataFrame(nwmeasure)], ignore_index=True, axis=1) #아 column 이름 재설정 해야겠다..

## merge with label

In [103]:
label = pd.read_csv('../../multimodality_data/mor_final.csv')

In [104]:
label[['subjectkey','female']]

subjectkey  female
0     NDARINV003RTV85     1.0
1     NDARINV00BD7VDC     0.0
2     NDARINV00CY2MDM     0.0
3     NDARINV00HEV6HB     0.0
4     NDARINV00LH735Y     0.0
...               ...     ...
7735  NDARINVZZLZCKAY     1.0
7736  NDARINVZZNX6W2P     0.0
7737  NDARINVZZZ2ALR6     1.0
7738  NDARINVZZZNB0XC     1.0
7739  NDARINVZZZP87KR     1.0

[7740 rows x 2 columns]

In [91]:
df.rename(columns = {0: "subjectkey",
                     1: "density",
                    2:'transitivity_wd',
                    3:'efficiency_wei',
                    4:'assortativity_wei',
                    5:'rich_club_wd',
                    6:'core_periphery_dir',
                    7:'charpath'}, inplace=True)

In [92]:
df

subjectkey   density  transitivity_wd  efficiency_wei  \
0     NDARINV897CW9GM  1.020833         0.001306       -0.000039   
1     NDARINV43P39GXX  1.019947         0.002887        0.000001   
2     NDARINV8HMHK4GC  1.019947         0.001063       -0.000011   
3     NDARINVEZNGVY2P  1.019947         0.001459        0.000012   
4     NDARINV4L9UBRH1  1.019947         0.001484       -0.000042   
...               ...       ...              ...             ...   
8175  NDARINVCTM83NPV  1.020833         0.001093        0.000003   
8176  NDARINV7EGEBVF3  1.019504         0.000196       -0.000018   
8177  NDARINVXAU39X13  1.021277         0.001977       -0.000050   
8178  NDARINVNA0D3G9K  1.021277         0.003246       -0.000031   
8179  NDARINVAFVV598X  1.021277         0.002379        0.000070   

      assortativity_wei  rich_club_wd  core_periphery_dir  charpath  
0              0.030123     -0.748686            0.138000  0.005905  
1              0.057509     -0.248603            0.180287  0.008685  
2              0.144834     -0.628270            0.226213  0.006187  
3              0.079248     -0.694812            0.172987  0.006290  
4              0.073762     -0.548088            0.144023  0.006660  
...                 ...           ...                 ...       ...  
8175           0.125170     -0.745358            0.174010  0.005874  
8176           0.182286     -0.908010            0.268217  0.004583  
8177          -0.007564           NaN            0.179950  0.006380  
8178          -0.009457           NaN            0.169228  0.008493  
8179           0.022111           NaN            0.194633  0.007606  

[8180 rows x 8 columns]

In [105]:
label_df = pd.merge(label[['subjectkey','female']], df, how='inner', on='subjectkey')

In [106]:
label_df

subjectkey  female   density  transitivity_wd  efficiency_wei  \
0     NDARINV00HEV6HB     0.0  1.021277         0.003328       -0.000006   
1     NDARINV00LH735Y     0.0  1.020833         0.000711       -0.000030   
2     NDARINV00LJVZK2     0.0  1.020833        -0.000293       -0.000017   
3     NDARINV00U4FTRU     1.0  1.019504         0.000498       -0.000013   
4     NDARINV00U4FTRU     1.0  1.021277        -0.000162       -0.000028   
...               ...     ...       ...              ...             ...   
6701  NDARINVZZLZCKAY     1.0  1.021277         0.002422       -0.000019   
6702  NDARINVZZZ2ALR6     1.0  1.020833         0.001578       -0.000026   
6703  NDARINVZZZ2ALR6     1.0  1.021277         0.001406       -0.000005   
6704  NDARINVZZZNB0XC     1.0  1.019947        -0.000133       -0.000007   
6705  NDARINVZZZP87KR     1.0  1.020833         0.002029       -0.000043   

      assortativity_wei  rich_club_wd  core_periphery_dir  charpath  
0              0.001447           NaN            0.197838  0.008915  
1             -0.014755     -0.890495            0.366030  0.005265  
2              0.095211     -2.704654            0.388164  0.002308  
3              0.163811     -1.041093            0.358635  0.004587  
4              0.028982           NaN            0.605380  0.002272  
...                 ...           ...                 ...       ...  
6701           0.122827           NaN            0.168348  0.007356  
6702           0.163911     -0.610319            0.192672  0.006487  
6703           0.006259           NaN            0.185941  0.005779  
6704           0.142068     -1.461507            0.348381  0.003244  
6705           0.037417     -0.467269            0.229530  0.007157  

[6706 rows x 9 columns]

In [107]:
label_df.to_csv('rDCM_output_network_measure_labeled.csv')

In [109]:
new_df = label_df.dropna(axis=0)

## classification

In [131]:
from sklearn.model_selection import train_test_split # train/test set
from sklearn.metrics import accuracy_score, confusion_matrix # model 평가

### (1) model 생성

In [139]:
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis

In [140]:
names = [
    "Nearest Neighbors",
    "Linear SVM",
    "RBF SVM",
    "Gaussian Process",
    "Decision Tree",
    "Random Forest",
    "Neural Net",
    "AdaBoost",
    "Naive Bayes",
    "QDA",
]

classifiers = [
    KNeighborsClassifier(3),
    SVC(kernel="linear", C=0.025),
    SVC(gamma=2, C=1),
    GaussianProcessClassifier(1.0 * RBF(1.0)),
    DecisionTreeClassifier(max_depth=5),
    RandomForestClassifier(max_depth=5, n_estimators=10, max_features=1),
    MLPClassifier(alpha=1, max_iter=1000),
    AdaBoostClassifier(),
    GaussianNB(),
    QuadraticDiscriminantAnalysis(),
]

### (2) data 생성

In [151]:
# 1. data loading & 변수 생성
X = new_df.iloc[:, 2:].values
y = new_df.iloc[:, 1].values.astype(np.int64)
# 2. train/test split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size = 0.1, random_state = 123)
# 랜덤하게 샘플링하되 특정 번호를 지정함으로써 반복해서 시도하더라도 항상 같도록!

x_train.shape # (105, 4)
y_train.shape # (3704,)

(4762,)

### (3) 결과 확인

In [152]:
ans={}
for i, j in zip(names, classifiers):
    # 3. model
    model = j
    model.fit(X=x_train, y=y_train)

    # 4. model 평가
    y_pred = model.predict(x_test) # 예측치
    y_true = y_test # 정답

    # 분류정확도 - accuracy_score 함수 사용해서 구하기
    acc = accuracy_score(y_true, y_pred)
    ans[str(i)] = acc

In [158]:
result=pd.DataFrame.from_dict(ans, orient='index')

In [159]:
result.rename(columns = {0: "accuracy"}, inplace=True)

In [160]:
result

accuracy
Nearest Neighbors  0.501887
Linear SVM         0.484906
RBF SVM            0.511321
Gaussian Process   0.528302
Decision Tree      0.513208
Random Forest      0.505660
Neural Net         0.484906
AdaBoost           0.500000
Naive Bayes        0.475472
QDA                0.479245

## Appendix

**Degree**
: Node degree is the number of links connected to the node. In directed networks, the in-degree is the number of inward links and the out-degree is the number of outward links. Connection weights are ignored in calculations.

- degrees_dir.m (BD, WD networks).

In [14]:
degree = bct.degrees_dir(sample['result'])

In [16]:
degree

(array([48., 48., 48., 48., 48., 48., 48., 48., 48., 48., 48., 48., 48.,
        48., 48., 48., 48., 48., 48., 48., 48., 48., 48., 48., 48., 48.,
        48., 48., 48., 48., 48., 48., 47., 48., 48., 48., 48., 48., 48.,
        48., 48., 47., 48., 48., 48., 48., 47., 48.]),
 array([48., 48., 48., 48., 48., 48., 48., 48., 48., 48., 48., 48., 48.,
        48., 48., 48., 48., 48., 48., 47., 48., 48., 48., 48., 48., 48.,
        48., 48., 48., 48., 48., 48., 48., 48., 48., 48., 48., 47., 48.,
        48., 48., 48., 48., 48., 47., 48., 48., 48.]),
 array([96., 96., 96., 96., 96., 96., 96., 96., 96., 96., 96., 96., 96.,
        96., 96., 96., 96., 96., 96., 95., 96., 96., 96., 96., 96., 96.,
        96., 96., 96., 96., 96., 96., 95., 96., 96., 96., 96., 95., 96.,
        96., 96., 95., 96., 96., 95., 96., 95., 96.]))

**Strength**: Node strength is the sum of weights of links connected to the node. In directed networks, the in-strength is the sum of inward link weights and the out-strength is the sum of outward link weights.

- strengths_dir.m (WD networks).

In [17]:
strength = bct.strengths_dir(sample['result'])

In [18]:
strength

array([-0.4035924 , -0.31764927, -0.44271753, -0.35222992, -0.29751368,
       -0.33139837, -0.42503962, -0.45443953, -0.38505723, -0.21041595,
       -0.41968178, -0.26054279, -0.23924198, -0.50340741, -0.4446705 ,
       -0.41257788, -0.35447472, -0.74843033, -0.45061899, -0.23139542,
       -0.3216253 , -0.496928  , -0.36304345, -0.36244998, -0.72726783,
       -0.6500496 , -0.83521071, -0.38456433, -0.28824089, -0.39684499,
       -0.4531086 , -0.45182763, -0.50716045, -0.51696171, -0.69193948,
       -0.37988999, -0.3634835 , -0.4080805 , -0.36325062, -0.36147737,
       -0.405823  , -0.09127808, -0.40687196, -0.30968731, -0.1098223 ,
       -0.11078836, -0.38100956, -0.46676392])

**Joint degree**: This function returns a matrix in which the value of each element (u,v) corresponds to the number of nodes that have u outgoing connections and v incoming connections. Connection weights are ignored.

- jdegree.m (BD, WD networks).

In [19]:
jdegree = bct.jdegree(sample['result'])

TypeError: 'numpy.float64' object cannot be interpreted as an integer

**Density**: Density is the fraction of present connections to possible connections. Connection weights are ignored in calculations.

- density_dir.m (BD, WD networks).

In [20]:
density = bct.density_dir(sample['result'])

In [79]:
density[0]

1.0199468085106382

**Clustering coefficient**: The clustering coefficient is the fraction of triangles around a node and is equivalent to the fraction of node’s neighbors that are neighbors of each other.

- clustering_coef_wd.m (WD networks);

In [23]:
clustering_coef_wd = bct.clustering_coef_wd(sample['result'])

In [24]:
clustering_coef_wd

array([ 9.74839826e-04,  1.02603716e-03,  9.41969312e-04,  2.19988730e-03,
        2.36334629e-03,  2.40746543e-03,  1.22073963e-03,  1.28031147e-03,
        2.26418104e-03,  1.92551615e-03,  1.61969954e-03,  1.10338372e-03,
        2.42941385e-03,  1.01928359e-03,  1.18627918e-03,  1.32922839e-03,
        1.89380428e-03, -1.82187924e-04,  6.67512852e-04,  2.58434999e-03,
        2.12335935e-03,  8.84476152e-04,  1.77493116e-03,  1.84809321e-03,
        2.02593325e-04,  1.98649905e-04, -1.69530778e-04,  1.55218291e-03,
        2.36033880e-03,  1.87532726e-03,  1.19106532e-03,  9.34204185e-04,
        1.08030889e-03,  1.00696496e-03,  5.46374224e-05,  1.31605310e-03,
        1.96686196e-03,  1.52734465e-03,  1.33861013e-03,  1.32406302e-03,
        1.42302528e-03,  2.88292827e-03,  1.35791022e-03,  1.62705542e-03,
        3.13441247e-03,  2.40447290e-03,  1.38165767e-03,  1.23537954e-03])

**Transitivity**: The transitivity is the ratio of triangles to triplets in the network and is an alternative to the clustering coefficient.

- transitivity_wd.m (WD networks).

In [25]:
transitivity_wd = bct.transitivity_wd(sample['result'])

In [26]:
transitivity_wd

0.0014585926946601836

**Local efficiency**: The local efficiency is the global efficiency (see below) computed on node neighborhoods, and is related to the clustering coefficient.

- efficiency_wei.m (WU, WD networks).

In [27]:
efficiency_wei = bct.efficiency_wei(sample['result'])

In [28]:
efficiency_wei

1.1636754699001931e-05

**Community structure and modularity**: The optimal community structure is a subdivision of the network into nonoverlapping groups of nodes in a way that maximizes the number of within-group edges, and minimizes the number of between-group edges. The modularity is a statistic that quantifies the degree to which the network may be subdivided into such clearly delineated groups.

- community_louvain.m (BU, WU, BD, WD, signed networks): Louvain community detection algorithm with added finetuning.

- modularity_dir.m (BD, WD networks): Newman's spectral community detection.

- link_communities.m (BU, WU, BD, WD networks): Link-based community-detection algorithm (detects overlapping communities).

In [29]:
community_louvain = bct.community_louvain(sample['result'])

BCTParamError: Input connection matrix contains negative weights but objective function dealing with negative weights was not selected

In [30]:
modularity = bct.modularity_dir(sample['result'])

In [154]:
modularity[-1]

-1.3530843112619095e-16

In [32]:
link_communities = bct.link_communities(sample['result'])

hierarchy 0
hierarchy 1


/home/connectome/stellasybae/anaconda3/lib/python3.7/site-packages/bct/algorithms/modularity.py:414: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  unq_rows = np.vstack({tuple(row) for row in ug_rows})


hierarchy 2
hierarchy 3
hierarchy 4
hierarchy 5
hierarchy 6
hierarchy 7
hierarchy 8
hierarchy 9
hierarchy 10
hierarchy 11
hierarchy 12
hierarchy 13
hierarchy 14
hierarchy 15
hierarchy 16
hierarchy 17
hierarchy 18
hierarchy 19
hierarchy 20
hierarchy 21
hierarchy 22
hierarchy 23
hierarchy 24
hierarchy 25
hierarchy 26
hierarchy 27
hierarchy 28
hierarchy 29
hierarchy 30
hierarchy 31
hierarchy 32
hierarchy 33
hierarchy 34
hierarchy 35
hierarchy 36
hierarchy 37
hierarchy 38
hierarchy 39
hierarchy 40
hierarchy 41
hierarchy 42
hierarchy 43
hierarchy 44
hierarchy 45
hierarchy 46
hierarchy 47
hierarchy 48
hierarchy 49
hierarchy 50
hierarchy 51
hierarchy 52
hierarchy 53
hierarchy 54
hierarchy 55
hierarchy 56
hierarchy 57
hierarchy 58
hierarchy 59
hierarchy 60
hierarchy 61
hierarchy 62
hierarchy 63
hierarchy 64
hierarchy 65
hierarchy 66
hierarchy 67
hierarchy 68
hierarchy 69
hierarchy 70
hierarchy 71
hierarchy 72
hierarchy 73
hierarchy 74
hierarchy 75
hierarchy 76
hierarchy 77
hierarchy 78
hierarc

hierarchy 596
hierarchy 597
hierarchy 598
hierarchy 599
hierarchy 600
hierarchy 601
hierarchy 602
hierarchy 603
hierarchy 604
hierarchy 605
hierarchy 606
hierarchy 607
hierarchy 608
hierarchy 609
hierarchy 610
hierarchy 611
hierarchy 612
hierarchy 613
hierarchy 614
hierarchy 615
hierarchy 616
hierarchy 617
hierarchy 618
hierarchy 619
hierarchy 620
hierarchy 621
hierarchy 622
hierarchy 623
hierarchy 624
hierarchy 625
hierarchy 626
hierarchy 627
hierarchy 628
hierarchy 629
hierarchy 630
hierarchy 631
hierarchy 632
hierarchy 633
hierarchy 634
hierarchy 635
hierarchy 636
hierarchy 637
hierarchy 638
hierarchy 639
hierarchy 640
hierarchy 641
hierarchy 642
hierarchy 643
hierarchy 644
hierarchy 645
hierarchy 646
hierarchy 647
hierarchy 648
hierarchy 649
hierarchy 650
hierarchy 651
hierarchy 652
hierarchy 653
hierarchy 654
hierarchy 655
hierarchy 656
hierarchy 657
hierarchy 658
hierarchy 659
hierarchy 660
hierarchy 661
hierarchy 662
hierarchy 663
hierarchy 664
hierarchy 665
hierarchy 666
hierar

In [33]:
link_communities

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

**Modularity degeneracy and consensus partitioning**: Modularity degeneracy is the existence of multiple distinct high-modularity partitions of the same network. Consensus partitioning aims to provide a single consensus partition of these degenerate partitions.

- agreement.m, agreement_weighted.m (BU, BD, WU, WD networks).
- consensus_und.m (BU, BD, WU, WD networks).

In [37]:
agreement = bct.agreement(sample['result'])

In [38]:
agreement

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [39]:
consensus_und = bct.consensus_und(sample['result'])

TypeError: consensus_und() missing 1 required positional argument: 'tau'

**Assortativity**: The assortativity coefficient is a correlation coefficient between the degrees of all nodes on two opposite ends of a link. A positive assortativity coefficient indicates that nodes tend to link to other nodes with the same or similar degree.

- assortativity_wei.m (WU, WD networks).

In [41]:
assortativity_wei = bct.assortativity_wei(sample['result'])

In [42]:
assortativity_wei

0.0792479016053189

**Rich club coefficient**: The rich club coefficient at level k is the fraction of edges that connect nodes of degree k or higher out of the maximum number of edges that such nodes might share.

- rich_club_wd.m (WD networks).

In [43]:
rich_club_wd = bct.rich_club_wd(sample['result'])

In [45]:
rich_club_wd[-1]

-0.694811600938646

**Core/periphery structure**: The core/periphery subdivision is a partition of the network into two non-overlapping groups of nodes, a core group and a periphery group, in a way that maximizes the number/weight of within core-group edges, and minimizes the number/weight of within periphery-group edges.

- core_periphery_dir.m (BU, BD, WU, WD networks).

In [46]:
core_periphery_dir = bct.core_periphery_dir(sample['result'])

In [48]:
core_periphery_dir[-1]

0.17298669887663948

**Distance and characteristic path length**: The reachability matrix describes whether pairs of nodes are connected by paths (reachable). The distance matrix contains lengths of shortest paths between all pairs of nodes. The characteristic path length is the average shortest path length in the network.


- retrieve_shortest_path.m (BU, BD, WU, WD networks): sequence of nodes that comprise the shortest path between a given source and target node.

- distance_wei.m (WU, WD networks): distance matrix (Dijkstra's algorithm). The input matrix must be a mapping from weight to distance (usually weight inversion).

- distance_wei_floyd.m (BU, BD, WU, WD networks): distance matrix (Floyd-Warshall algorithm). The input matrix may be a mapping from weight to distance (usually weight inversion), or may be the native weights matrix (in which case a weight transform to distance must be specified as the input).

In [49]:
retrieve_shortest_path = bct.retrieve_shortest_path(sample['result'])

TypeError: retrieve_shortest_path() missing 3 required positional arguments: 't', 'hops', and 'Pmat'

In [51]:
distance_wei = bct.distance_wei(sample['result'])

In [54]:
distance_wei

(array([[ 0.        , -0.04913654, -0.07190607, ..., -0.07231138,
         -0.05216059, -0.05822592],
        [-0.0488108 ,  0.        , -0.05375218, ..., -0.05415748,
         -0.0340067 , -0.04007202],
        [-0.06410752, -0.04670857,  0.        , ..., -0.06293477,
         -0.04973262, -0.05579794],
        ...,
        [-0.07167493, -0.03035975, -0.07862816, ...,  0.        ,
         -0.05164694, -0.05771227],
        [-0.05754927, -0.05197574, -0.06352728, ..., -0.06393259,
          0.        , -0.05340852],
        [-0.05014855, -0.01354076, -0.05710178, ..., -0.05750709,
         -0.03482796,  0.        ]]),
 array([[ 0.,  7., 16., ..., 18.,  9., 11.],
        [19.,  0., 16., ..., 18.,  9., 11.],
        [17.,  7.,  0., ..., 16.,  9., 11.],
        ...,
        [29.,  4., 27., ...,  0., 10., 12.],
        [20.,  9., 19., ..., 21.,  0., 14.],
        [22.,  2., 20., ..., 22.,  8.,  0.]]))

In [55]:
distance_wei_floyd = bct.distance_wei_floyd(sample['result'])

In [56]:
distance_wei_floyd

(array([[        0.        , -49725764.03887663, -49725764.0297811 , ...,
         -49725764.02602097, -49725764.03423081, -49725764.03326623],
        [-49725764.02134572,         0.        , -49725764.02101564, ...,
         -49725764.01725551, -49725764.02546535, -49725764.02450078],
        [-49725764.03044126, -49725764.03920671,         0.        , ...,
         -49725764.02635106, -49725764.0345609 , -49725764.03359632],
        ...,
        [-49725764.0276958 , -49725764.03646126, -49725764.02736572, ...,
                 0.        , -49725764.03181544, -49725764.03085086],
        [-49725764.03408381, -49725764.04284927, -49725764.03375374, ...,
         -49725764.02999361,         0.        , -49725764.03723887],
        [-49725764.03187849, -49725764.04064395, -49725764.03154841, ...,
         -49725764.02778828, -49725764.03599812,         0.        ]]),
 array([[0.00000000e+00, 6.67224761e+10, 6.67224761e+10, ...,
         6.67224761e+10, 6.67224761e+10, 6.67224761e+10],
 

**Characteristic path length, global efficiency, eccentricity, radius, diameter**: The characteristic path length is the average shortest path length in the network. The global efficiency is the average inverse shortest path length in the network. The node eccentricity is the maximal shortest path length between a node and any other node. The radius is the minimum eccentricity and the diameter is the maximum eccentricity.

- charpath.m (BU, BD, WU, WD networks).

In [57]:
charpath = bct.charpath(sample['result'])

/home/connectome/stellasybae/anaconda3/lib/python3.7/site-packages/bct/algorithms/distance.py:157: RuntimeWarning: divide by zero encountered in true_divide
  efficiency = np.mean(1 / Dv)


In [59]:
charpath[0]

0.006290498076555876

**Global and local efficiency**: The global efficiency is the average inverse shortest path length in the network, and is inversely related to the characteristic path length. The local efficiency is the global efficiency computed on the neighborhood of the node, and is related to the clustering coefficient.

- efficiency_wei.m (WU, WD networks)
- rout_efficiency.m (BU, BD, WU, WD networks).

In [60]:
efficiency_wei = bct.efficiency_wei(sample['result'])

In [61]:
efficiency_wei

1.1636754699001931e-05

In [78]:
rout_efficiency = bct.rout_efficiency(sample['result'])

AttributeError: module 'bct' has no attribute 'rout_efficiency'

**Mean first passage time**: The first passage time is the expected number of steps it takes a random walker to reach one node from another.

- mean_first_passage_time.m (BU, BD, WU, WD networks).

In [74]:
mean_first_passage_time = bct.mean_first_passage_time(sample['result'])

In [77]:
mean_first_passage_time.shape

(48, 48)

**Diffusion efficiency**: The diffusion efficiency is the inverse of the mean first passage time.

- diffusion_efficiency.m (BU, BD, WU, WD networks).

In [72]:
diffusion_efficiency = bct.diffusion_efficiency(sample['result'])

AttributeError: module 'bct' has no attribute 'diffusion_efficiency'

**Betweenness centrality**: Node betweenness centrality is the fraction of all shortest paths in the network that contain a given node. Nodes with high values of betweenness centrality participate in a large number of shortest paths.

- betweenness_wei.m (WU, WD networks): Brandes's algorithm.

In [70]:
betweenness_wei = bct.betweenness_wei(sample['result'])

In [71]:
betweenness_wei

array([  30.,    0.,  738.,    0.,   21.,    0.,  165.,  207.,  224.,
          6., 1549.,    0.,    0., 1809., 1507.,  885.,  354., 1955.,
       2036.,  109.,  145.,  681.,   10.,  408.,  963., 1844., 1852.,
         78.,    0.,  290.,    0., 1644., 2018.,  427., 2063.,  753.,
        575.,   18.,  375.,  755.,  287.,  466., 1529.,  353.,   22.,
         28., 1652., 1517.])

**Edge betweenness centrality**: Edge betweenness centrality is the fraction of all shortest paths in the network that contain a given edge. Edges with high values of betweenness centrality participate in a large number of shortest paths.

- edge_betweenness_wei.m (WU, WD networks).

In [68]:
edge_betweenness_wei = bct.edge_betweenness_wei(sample['result'])

In [69]:
edge_betweenness_wei

(array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]),
 array([  30.,    0.,  738.,    0.,   21.,    0.,  165.,  207.,  224.,
           6., 1549.,    0.,    0., 1809., 1507.,  885.,  354., 1955.,
        2036.,  109.,  145.,  681.,   10.,  408.,  963., 1844., 1852.,
          78.,    0.,  290.,    0., 1644., 2018.,  427., 2063.,  753.,
         575.,   18.,  375.,  755.,  287.,  466., 1529.,  353.,   22.,
          28., 1652., 1517.]))

**Within-module degree z-score**: The within-module degree z-score is a within-module version of degree centrality. This measure requires a previously determined community structure (see above).

- module_degree_zscore.m; (BU, BD, WU, WD networks).

In [66]:
module_degree_zscore = bct.module_degree_zscore(sample['result'])

TypeError: module_degree_zscore() missing 1 required positional argument: 'ci'

**Participation and related coefficients**: Participation coefficient is a measure of diversity of intermodular connections of individual nodes. The gateway coefficient is a variant of the participation coefficient, weighted by the importance of individual connections. The diversity coefficient is a related measure, based on the Shannon entropy. All measures requires a previously determined community structure as input (see above).

- participation_coef.m (BU, BD, WU, WD networks).

In [65]:
participation_coef = bct.participation_coef(sample['result'])

TypeError: participation_coef() missing 1 required positional argument: 'ci'

In [ ]:
participation_coef

**Structural motifs**: Structural motifs (or simply motifs) are small (e.g. 3 or 4 node) patterns of local connectivity that occur in the network with a statistically surprising frequency. In weighted networks, the motif frequency may be supplemented by its weighted generalizations, the motif intensity and the motif coherence.

- motif3struct_wei.m; motif4struct_wei.m (WD networks).

In [64]:
motif3struct_wei = bct.motif3struct_wei(sample['result'])

FileNotFoundError: [Errno 2] No such file or directory: '/home/connectome/stellasybae/anaconda3/lib/python3.7/site-packages/bct/algorithms/motif34lib.mat'

In [ ]:
motif3struct_wei

**Functional motifs**: Functional motifs are subsets of connection patterns embedded within structural motifs. Functional motif frequency is the frequency of functional motif occurence around a node. In weighted networks, the motif frequency may be supplemented by its weighted generalizations, the motif intensity and the motif coherence.

- motif3funct_wei.m; motif4funct_wei.m (WD networks).

In [63]:
motif3funct_wei = bct.motif3funct_wei(sample['result'])

FileNotFoundError: [Errno 2] No such file or directory: '/home/connectome/stellasybae/anaconda3/lib/python3.7/site-packages/bct/algorithms/motif34lib.mat'

In [ ]:
motif4funct_wei